name: Multiple Cron jobs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  multiple-cron-jobs: 
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.5
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          
   

  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
